### ISSUE TITLE
http.delete redirects to options

### ISSUE THREAD

**Issue by lakiefer** [jorditost/node-postgres-restapi#3]
Does someone now how to allow GET,PUT,POST,DELETE?

In Postman it is working, but my Angular App calls DELETE and reaches OPTIONS on the server. I don't really now why.

**Comment by JustGiveItATry** [comment]
This solved my problem.
I found out that it is normal to call http-options. This way the client can ask for all the available http-verbs.
The problem was that i didn't configure my Access-Control-Allow-Methods in the header.

app.use(function (req, res, next) {
  // Website you wish to allow to connect
  res.setHeader('Access-Control-Allow-Origin', '*');
  // Request methods you wish to allow
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, HEAD, OPTIONS');
  // Request headers you wish to allow
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,origin,content-type');
  // Set to true if you need the website to include cookies in the requests sent
  // to the API (e.g. in case you use sessions)
  res.setHeader('Access-Control-Allow-Credentials', true);
  // Pass to next layer of middleware
  next();
});

https://stackoverflow.com/questions/18310394/no-access-control-allow-origin-node-apache-port-issue Posted from:jvandemo
